// <auto-generated />
using System;
using F1.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace F1.Infrastructure.Migrations
{
    [DbContext(typeof(F1DbContext))]
    [Migration("20260707184503_RemoveImportRunIdFromQuestionTables")]
    partial class RemoveImportRunIdFromQuestionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("F1.Core.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Competitions", (string)null);
                });

            modelBuilder.Entity("F1.Core.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PermanentNumber")
                        .HasColumnType("integer");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("F1.Core.Models.Race", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinalDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PreQualyDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Season", "Round")
                        .IsUnique();

                    b.ToTable("Races", (string)null);
                });

            modelBuilder.Entity("F1.Core.Models.Selection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RaceId", "UserId")
                        .IsUnique();

                    b.ToTable("Selections", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportCalculatedScoreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("PredictedValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RaceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RaceCode", "PickType", "Subject", "RowNumber")
                        .IsUnique();

                    b.ToTable("MigrationImportCalculatedScores", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportCalculatedTotalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculatedTotalPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportCalculatedTotals", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportConflictDiagnosticEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyFields")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PolicyOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "EntityType", "KeyFields");

                    b.ToTable("MigrationImportConflictDiagnostics", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportImportedTotalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ImportedTotalPoints")
                        .HasColumnType("integer");

                    b.Property<string>("RawTotal")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportImportedTotals", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportJolpicaRaceSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CircuitName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Season", "Round")
                        .IsUnique();

                    b.ToTable("MigrationImportJolpicaRaceSnapshots", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportLegacyPickScoreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LegacyPoints")
                        .HasColumnType("integer");

                    b.Property<string>("PickType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RaceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RawLegacyPoints")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RaceCode", "PickType", "Subject", "RowNumber")
                        .IsUnique();

                    b.ToTable("MigrationImportLegacyPickScores", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportParticipantDeltaSummaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculatedTotalPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("ImportedTotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("NetDeltaPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TopReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TopReasonCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportParticipantDeltaSummaries", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPickDiffEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CalculatedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DeltaPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectedVarianceReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExpectedVarianceRuleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ImportedPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExpectedVariance")
                        .HasColumnType("boolean");

                    b.Property<string>("PickType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RaceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RaceCode", "Subject", "PickType")
                        .IsUnique();

                    b.ToTable("MigrationImportPickDiffs", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonAnswerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActualOutcome")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedAnswer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool?>("NormalizedAnswerBoolean")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RawAnswer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RowNumber", "QuestionKey", "Subject", "IsActualOutcome")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonAnswers", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonCalculatedScoreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("PredictedValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RowNumber", "QuestionKey", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonCalculatedScores", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonCalculatedTotalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculatedTotalPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonCalculatedTotals", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonImportedTallyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ImportedPoints")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RawPoints")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RowNumber", "QuestionKey", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonImportedTallies", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonParticipantDeltaSummaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculatedTotalPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("ImportedTotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("NetDeltaPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TopReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TopReasonCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonParticipantDeltaSummaries", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonPolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CellReference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PointsPerQuestion")
                        .HasColumnType("integer");

                    b.Property<string>("RawPointsPerQuestion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonPolicies", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonQuestionDiffEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CalculatedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DeltaPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ImportedPoints")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RowNumber", "QuestionKey", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonQuestionDiffs", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonReasonCategorySummaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalDeltaPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "ReasonCode")
                        .IsUnique();

                    b.ToTable("MigrationImportPreseasonReasonCategorySummaries", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRaceDiffEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculatedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DeltaPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectedVarianceReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExpectedVarianceRuleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("ImportedPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExpectedVariance")
                        .HasColumnType("boolean");

                    b.Property<string>("RaceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RaceCode", "Subject")
                        .IsUnique();

                    b.ToTable("MigrationImportRaceDiffs", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRaceRoundMappingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("MappedCircuitId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MappedRaceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RaceSequence")
                        .HasColumnType("integer");

                    b.Property<int?>("Round")
                        .HasColumnType("integer");

                    b.Property<int?>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("SourceRaceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Warning")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RaceSequence")
                        .IsUnique();

                    b.ToTable("MigrationImportRaceRoundMappings", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRaceSelectionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActualOutcome")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PickType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RaceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RaceCode", "PickType", "Subject", "RowNumber")
                        .IsUnique();

                    b.ToTable("MigrationImportRaceSelections", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRawRowEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassificationReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RowNumber")
                        .IsUnique();

                    b.ToTable("MigrationImportRawRows", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportReasonCategorySummaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalDeltaPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "ReasonCode")
                        .IsUnique();

                    b.ToTable("MigrationImportReasonCategorySummaries", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRollbackAuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("AffectedRaceCount")
                        .HasColumnType("integer");

                    b.Property<int>("AffectedSelectionCount")
                        .HasColumnType("integer");

                    b.Property<int>("AffectedSelectionPositionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RequestedAtUtc");

                    b.ToTable("MigrationImportRollbackAudits", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IdempotencyScopeKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean");

                    b.Property<int>("MappingWarningCount")
                        .HasColumnType("integer");

                    b.Property<string>("ParityComparedChecksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParityComparedRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParitySnapshotChecksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PreseasonAnswerCount")
                        .HasColumnType("integer");

                    b.Property<int>("PreseasonErrorCount")
                        .HasColumnType("integer");

                    b.Property<bool>("PreseasonIsolationGuardPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreseasonParseStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PreseasonQuestionDiffCount")
                        .HasColumnType("integer");

                    b.Property<int>("PreseasonScoredQuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("PreseasonScoringStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PreseasonTotalDeltaPoints")
                        .HasColumnType("integer");

                    b.Property<int>("PreseasonWarningCount")
                        .HasColumnType("integer");

                    b.Property<int>("RawRowCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFileChecksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UnresolvedTokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileChecksum");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("MigrationImportRuns", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportUnresolvedTokenEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RaceCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RawToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "RowNumber", "RaceCode", "PickType", "Subject", "RawToken")
                        .IsUnique();

                    b.ToTable("MigrationImportUnresolvedTokens", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionActualEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualAnswer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NormalizationDiagnosticsJson")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedAnswer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool?>("NormalizedAnswerBoolean")
                        .HasColumnType("boolean");

                    b.Property<long>("QuestionTemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceColumn")
                        .HasColumnType("integer");

                    b.Property<int>("SourceRow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTemplateId")
                        .IsUnique();

                    b.HasIndex("SourceRow", "SourceColumn");

                    b.ToTable("QuestionActuals", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionAnswerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ImportedAnswer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NormalizedAnswer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool?>("NormalizedAnswerBoolean")
                        .HasColumnType("boolean");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("QuestionTemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceColumn")
                        .HasColumnType("integer");

                    b.Property<int>("SourceRow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTemplateId", "ParticipantId")
                        .IsUnique();

                    b.HasIndex("SourceRow", "SourceColumn");

                    b.ToTable("QuestionAnswers", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionScoreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CalculatedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("DeltaPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("ImportedPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("QuestionTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeltaPoints");

                    b.HasIndex("QuestionTemplateId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("QuestionScores", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionTemplateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Season", "QuestionId")
                        .IsUnique();

                    b.HasIndex("CompetitionId", "Season", "Category", "SortOrder");

                    b.ToTable("QuestionTemplates", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.RaceMetadataEntity", b =>
                {
                    b.Property<string>("RaceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BonusQuestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("H2HQuestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RaceId");

                    b.ToTable("RaceMetadata", (string)null);
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.SelectionPositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("SelectionId", "Position")
                        .IsUnique();

                    b.ToTable("SelectionPositions", (string)null);
                });

            modelBuilder.Entity("F1.Core.Models.Race", b =>
                {
                    b.HasOne("F1.Core.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Core.Models.Selection", b =>
                {
                    b.HasOne("F1.Core.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportCalculatedScoreEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportCalculatedTotalEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportConflictDiagnosticEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportImportedTotalEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportJolpicaRaceSnapshotEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportLegacyPickScoreEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportParticipantDeltaSummaryEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPickDiffEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonAnswerEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonCalculatedScoreEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonCalculatedTotalEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonImportedTallyEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonParticipantDeltaSummaryEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonPolicyEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonQuestionDiffEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportPreseasonReasonCategorySummaryEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRaceDiffEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRaceRoundMappingEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRaceSelectionEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRawRowEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportReasonCategorySummaryEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportRollbackAuditEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.MigrationImportUnresolvedTokenEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.MigrationImportRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionActualEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.QuestionTemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionAnswerEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.QuestionTemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionScoreEntity", b =>
                {
                    b.HasOne("F1.Infrastructure.Data.Entities.QuestionTemplateEntity", null)
                        .WithMany()
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.QuestionTemplateEntity", b =>
                {
                    b.HasOne("F1.Core.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.RaceMetadataEntity", b =>
                {
                    b.HasOne("F1.Core.Models.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1.Infrastructure.Data.Entities.SelectionPositionEntity", b =>
                {
                    b.HasOne("F1.Core.Models.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1.Core.Models.Selection", null)
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
